plugins {
    id 'gradle-plugin-conventions'
    id 'maven-publish'
}

dependencies {
    implementation "com.github.ben-manes:gradle-versions-plugin:${gradleVersionsPluginVersion}"
    implementation "com.adarshr:gradle-test-logger-plugin:${testLoggerPluginVersion}"
}

gradlePlugin {
    plugins {
        laaJavaPlugin {
            id = 'uk.gov.justice.service.laa.laa-java-gradle-plugin'
            implementationClass = 'uk.gov.laa.gradle.LaaJavaGradlePlugin'
        }
    }
}
