name: Build feature

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-publish-snapshot:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/gradle-build-and-publish.yml@4daa796eff475c7a107e17daf4e4882b8a1b949b # v2.3.0
    permissions:
      contents: write
      packages: write
    with:
      java_version: '25'
      java_distribution: 'corretto'
      release_type: 'snapshot'
      junit_results: 'false'
      junit_report: 'false'
      checkstyle_report: 'false'
      jacoco_coverage_report: 'false'
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
