name: Lint PR title

on:
  pull_request:
    branches: [ main ]
    types: [ opened, edited, synchronize, reopened ]

jobs:
  lint-pr-title:
    uses: ministryofjustice/laa-ccms-common-workflows/.github/workflows/lint-pr-title.yml@chore/LJCP-27_release_plugin # TODO: pin to SHA on merge
